#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the list of staged files
staged_files=$(git diff --name-only --cached)

# Loop through the staged files and extract the folder names
folders=()
for file in $staged_files; do
  folder=$(dirname "$file")
  folders+=("$folder")
done

# Remove duplicate folder names
unique_folders=($(echo "${folders[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

if [[ " ${unique_folders[@]} " =~ "web" ]]; then
  echo "📚  web folder is being updated, running web pre-commit hook"
  yarn u lint
  yarn u format
  yarn u build
  yarn u testOnce
fi

if [[ " ${unique_folders[@]} " =~ "backend" ]]; then
  echo "📚  backend folder is being updated, running backend pre-commit hook"
  yarn u lint
  yarn u format
  yarn u build
  yarn u testOnce
fi
